/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mrms;

import static com.mycompany.mrms.Home.loggedInPatientID;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author patok
 */
public class CreateNewRecord extends javax.swing.JFrame {

    private static int loggedInPatientID;
    private static final String DRIVER = "com.mysql.cj.jdbc.Driver";
    private static final String DATABASE_URL = "jdbc:mysql://localhost:3306/db_mrms";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "admin";
    private Connection mrms_db = null;

    public CreateNewRecord() {
        initComponents();
        connectDB();
    }

    public CreateNewRecord(int loggedInPatientID) {
        this.loggedInPatientID = loggedInPatientID;
        initComponents();
        connectDB();
    }

    private void connectDB() {
        try {
            Class.forName(DRIVER);
            mrms_db = DriverManager.getConnection(DATABASE_URL, USERNAME, PASSWORD);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Error connecting to database: " + e.getMessage());
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(4, 59, 92));
        setMinimumSize(new java.awt.Dimension(1050, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 180, 45));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 130));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 59, 92));
        jLabel2.setText("MRMS Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(411, 411, 411))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Create New Medical Record");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 240, 30));

        jTextField1.setText("N/A");
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 160, 70));

        jTextField2.setText("N/A");
        jTextField2.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 400, 70));

        jTextField3.setText("N/A");
        jTextField3.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 70));

        jTextField4.setText("N/A");
        jTextField4.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 70));

        jTextField5.setText("N/A");
        jTextField5.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 160, 70));

        jTextField6.setText("N/A");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 130, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 190, 130, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 130, -1));

        jTextField9.setText("N/A");
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 130, -1));

        jLabel8.setText("Notes");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabel10.setText("Mother Blood Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel11.setText("Father's Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        jLabel12.setText("Father's Blood Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 130, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 130, -1));

        jTextField12.setText("dd/mm/yyyy");
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 130, -1));

        jTextField13.setText("dd/mm/yyyy");
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, 130, -1));

        jLabel13.setText("Mother's Surname");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jLabel14.setText("Mother DOB");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel15.setText("Father's Surname");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        jLabel16.setText("Father's DOB");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        jLabel17.setText("Mother's Name");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel18.setText("Diagnosis");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel19.setText("Immunization History");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel20.setText("Allergies");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel21.setText("Prescriptions");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jTextField14.setText("N/A");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 130, -1));

        jLabel22.setText("Patient's Blood Type");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));

        jLabel23.setText("All fields");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, 10));

        jLabel25.setText("are mandatory.");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setText("*");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 10, 20));

        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("*");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 10, 10));

        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setText("*");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 10, 10));

        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("*");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 10, 10));

        jLabel31.setForeground(new java.awt.Color(255, 0, 51));
        jLabel31.setText("*");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 10, 10));

        jLabel32.setForeground(new java.awt.Color(255, 0, 51));
        jLabel32.setText("*");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 10, 10));

        jTextField15.setText("N/A");
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 310, 130, -1));

        jLabel33.setText("Paternal Hereditary Disease");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 150, -1));

        jTextField16.setText("N/A");
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 130, 20));

        jLabel34.setText("Maternal Hereditary Disease");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 150, -1));

        jButton2.setText("CREATE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 40));

        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        this.dispose();
        Home.loggedInPatientID = loggedInPatientID; // Get the logged-in patient ID
        MedicalRecord mr = new MedicalRecord(loggedInPatientID); // Pass PatientID to constructor
        mr.setVisible(true); // Display the MedicalRecord frame
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // Retrieve data from text fields
        String diagnosis = jTextField3.getText().trim();
        String allergies = jTextField1.getText().trim();
        String immunizationHistory = jTextField4.getText().trim();
        String notes = jTextField2.getText().trim();
        String prescriptions = jTextField5.getText().trim();
        String motherName = jTextField8.getText().trim();
        String motherSurname = jTextField10.getText().trim();
        String motherDOB = jTextField12.getText().trim();
        String motherBloodType = jTextField6.getText().trim();
        String maternalHereditaryDisease = jTextField16.getText().trim();
        String fatherName = jTextField7.getText().trim();
        String fatherSurname = jTextField11.getText().trim();
        String fatherDOB = jTextField13.getText().trim();
        String fatherBloodType = jTextField9.getText().trim();
        String paternalHereditaryDisease = jTextField15.getText().trim();
        String patientBloodType = jTextField14.getText().trim();

        // Use the logged-in patient ID from Home.java
        int patientID = loggedInPatientID;

        // Check if the patient exists
        if (!patientExists(patientID)) {
            JOptionPane.showMessageDialog(null, "Patient with ID " + patientID + " does not exist.");
            return;
        }

        // Retrieve patient's first name and last name
        String[] patientNames = getPatientNames(patientID);
        if (patientNames == null) {
            JOptionPane.showMessageDialog(null, "Error retrieving patient's names.");
            return;
        }

        // SQL insert statement
        String sql = "INSERT INTO medicalrecords (FirstName, LastName, Diagnosis, Allergies, ImmunizationHistory, Notes, Prescriptions, "
        + "MotherName, MotherSurname, MotherDOB, MotherBloodType, MaternalHereditaryDisease, "
        + "FatherName, FatherSurname, FatherDOB, FatherBloodType, PaternalHereditaryDisease, "
        + "PatientBloodType, PatientID) "
        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement pstmt = mrms_db.prepareStatement(sql)) {
            pstmt.setString(1, patientNames[0]); // FirstName
            pstmt.setString(2, patientNames[1]); // LastName
            pstmt.setString(3, diagnosis);
            pstmt.setString(4, allergies);
            pstmt.setString(5, immunizationHistory);
            pstmt.setString(6, notes);
            pstmt.setString(7, prescriptions);
            pstmt.setString(8, motherName);
            pstmt.setString(9, motherSurname);
            pstmt.setString(10, motherDOB);
            pstmt.setString(11, motherBloodType);
            pstmt.setString(12, maternalHereditaryDisease);
            pstmt.setString(13, fatherName);
            pstmt.setString(14, fatherSurname);
            pstmt.setString(15, fatherDOB);
            pstmt.setString(16, fatherBloodType);
            pstmt.setString(17, paternalHereditaryDisease);
            pstmt.setString(18, patientBloodType);
            pstmt.setInt(19, patientID);

            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Medical record created successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to create medical record.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error creating medical record: " + ex.getMessage());
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed
 public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            int loggedInPatientID = Home.getLoggedInPatientID(); // Assuming you have a method to get this ID
            new CreateNewRecord(loggedInPatientID).setVisible(true); // Pass loggedInPatientID to constructor
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
public static int getLoggedInPatientID() {
        return loggedInPatientID;
    }
private boolean patientExists(int patientID) {
        try {
            String sql = "SELECT COUNT(*) AS count FROM patients WHERE PatientID = ?";
            try (PreparedStatement ps = mrms_db.prepareStatement(sql)) {
                ps.setInt(1, patientID);
                try (ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        int count = rs.getInt("count");
                        return count > 0;
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error checking patient existence: " + e.getMessage());
            e.printStackTrace();
        }
        return false;
    }

 private String[] getPatientNames(int patientID) {
        String sql = "SELECT FirstName, LastName FROM patients WHERE PatientID = ?";
        try (PreparedStatement ps = mrms_db.prepareStatement(sql)) {
            ps.setInt(1, patientID);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String firstName = rs.getString("FirstName");
                    String lastName = rs.getString("LastName");
                    return new String[]{firstName, lastName};
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error retrieving patient names: " + e.getMessage());
            e.printStackTrace();
        }
        return null;
    }
}